### PR TITLE
fix slug generation

### LINKED ISSUE #272: Conflicting organization slugs
Planet and Planet+ have conflicting slugs

### PR DESCRIPTION
**Pull request by loiclefloch**
- add jest to unit test on src/
- modify slug generation to handle '+' char
- add slug unit test

Fixes #272

### CODE REVIEW

File: __mocks__/gatsby.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+// https://www.gatsbyjs.org/docs/unit-testing/
+const React = require("react")
+const gatsby = jest.requireActual("gatsby")
+module.exports = {
```
Comment (bloudermilk) [inline __mocks__/gatsby.js:4]: @jasonLaster has done some legwork in #218 to set up real integration tests for the frontend. My preference is to use Jest for "pure" JS functions as you've done in the case of `makeSlug` and keep the React testing in Cypress.

I think we can drop the default Gatsby mocks.

File: src/utils/slug.test.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
+const { makeSlug } = require("./slug.js")
+
+describe(`makeSlug()`, () => {
```
Comment (bloudermilk) [inline src/utils/slug.test.js:3]: Check out the configs in `enrich` to stop eslint/pretteir from complaining about this.

File: src/utils/slug.js [hunk 3]
```diff
@@ -1,8 +1,12 @@
...
-    .replace("&", "and")
-    .replace(/[^\w\- ]/g, "")
-    .replace(/ +/g, "-")
+  return (
+    string
+      .toLowerCase()
+      .trim()
+      .replace("&", "and")
+      // remove all non-alphanumeric chars and not-defined chars (+, -, etc)
+      .replace(/[^\w\-+ ]/g, "")
```
Comment (bloudermilk) [inline src/utils/slug.js:9]: I think a word replace might work better here, like we did with "&". Here are all the examples from our DB today:

* "100+ Accelerator" -> `100plus-acelerator` vs `100+-accelerator`
* "Terra Food + AG Tech Accelerator" -> `terra-food-plus-ag-tech-accelerator` vs `terra-food-+-ag-tech-accelerator`
* "Planet+" -> `planetplus` vs `planet+`

**Review by bloudermilk — COMMENTED** [review]
Thank you for using tests here, great to see us get that set up. In the near future I think we'll be moving away from just-in-time generated slugs to database-persisted and guaranteed unique slugs. Until then, I think approaching this as we've done is just fine.

**Comment by bloudermilk** [comment]
@loiclefloch ping, would be great to get this shipped 😄

**Comment by bloudermilk** [comment]
@loiclefloch a *long* time coming, but very happy to merge this PR. Thank you 🙏
