### PR TITLE
Separates capital-only orgs from others

### LINKED ISSUE #116: Separate capital and non-capital orgs
Now that we have a new "Capital" section that have filters exclusive to those types of orgs, we should not include them in other parts of the site, like the categories pages and "all orgs". The only exception is if an org that has the "Capital" role also has another role.

### PR DESCRIPTION
**Pull request by bloudermilk**
Capital orgs tend to dominate other orgs because they cover so many categories. Now that we have a dedicated "Capital" section, we can remove these orgs from our primary organizations list. Fixes #116

### CODE REVIEW

File: src/pages/organizations.js [hunk 1]
```diff
@@ -88,7 +88,17 @@ export const query = graphql`
...
-        data: { Categories: { elemMatch: { id: { eq: $categoryId } } } }
+        data: {
+          Role: {
+            in: [
+              "Products & Services"
+              "Research & Development"
+              "Advocacy"
+              "Network"
+            ]
+          }
```
Comment (jasonLaster) [inline src/pages/organizations.js]: It might be nice to use a separate airtable view, to keep this logic on the backend.

Comment (bloudermilk) [reply src/pages/organizations.js]: @jasonLaster I agree with your assessment here but it turns out not to be any easier to query this in Airtable. The rule we want is basically "Any org that has on or more Roles not equal to 'Capital'". I think we can roll with this for now.
